# Generated by Django 2.0.2 on 2018-03-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cell_phone',
            new_name='product_cost',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='client_number',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='city',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='address',
        ),
        migrations.RemoveField(
            model_name='product',
            name='email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='state',
        ),
        migrations.RemoveField(
            model_name='product',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='product',
            name='product_descr',
            field=models.CharField(default='null', max_length=250),
        ),
    ]
