# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-24 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180321_2104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
