# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-29 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
