# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-29 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20180429_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='entered_token',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
