# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-29 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_profile_entered_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileFilled',
            field=models.BooleanField(default=False),
        ),
    ]
