# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-29 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_profile_profilefilled'),
    ]

    operations = [
        migrations.CreateModel(
            name='activationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_token', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='entered_token',
        ),
        migrations.AddField(
            model_name='profile',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
